apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-redis
  name: myredis
spec:
  ports:
  - name: 6379-6379
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: ClusterIP
status:
  loadBalancer: {}
