apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service-server
  name: service-server
spec:
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: config-server
  type: ClusterIP
